### ISSUE TITLE
Segfault of unknown origin

### ISSUE THREAD

**Issue by schancel** [ikod/dlang-requests#31] opened 2016-12-02 20:32 UTC
I am writing a command line tool which scrapes a REST API. The following code, with vibed support turned on, segfaults during shutdown of the application.  If the `Request` struct is moved into the `Projects` function scope.   My presumption is that RestClient ends up finalized after some of the vibed internal objects, and during the RestClient finalization the rq struct is destroyed as well.  This may be accessing some vibed internals that are already gone?

```D
 class RestClient {
 	Request rq;

 	this(string user, string passwd) {
 		rq.verbosity = 0;
 		rq.authenticator = new BasicAuthentication(user, passwd);
 	}

 	auto Projects() {
 		auto rs = rq.get("https://xxxxx/rest/api/1.0/projects");
 		//auto pr = parseJsonString(rs.responseBody.to!string);

 		return "Hello";
 	}
}
```

**Comment by ikod** [comment] 2016-12-02 21:18
Hello @schancel 
Need some time to reproduce problem. Which versions of vibe.d, requests you have? and which OS, dmd?

**Comment by ikod** [comment] 2016-12-03 14:43
Hello, @schancel 

I can reproduce problem. It's origin lies in the some weird handling of socket close in vibe.d - I'll implement fix or workaround in dlang-requests, or will try to cooperate with vibe.d developers to find proper solution.

Meanwhile you can set **keepAlive** property for Request to **false**, this should fix the wrong behavior (confirm, please).

```d
  5 class RestClient {
  6      Request rq;
  7
  8      this(string user, string passwd) {
  9          rq.verbosity = 0;
 10          rq.keepAlive = false;
 11          rq.authenticator = new BasicAuthentication(user, passwd);
 12      }
 13
```

I'll ping you when this problem will be fixed.

Thanks for your report.

**Comment by ikod** [comment] 2016-12-04 11:09
Hello, @schancel 

You were correct when you wrote "My presumption is that RestClient ends up finalized after some of the vibed internal objects, and during the RestClient finalization the rq struct is destroyed as well. This may be accessing some vibed internals that are already gone?".

The problem is that each **rest** object (and **rq** structure) finalized when event loop already stopped. With plain vibe.d socket (if you use http request, not https) and keep-alive request (socket not closed when http request completed) you will just receive warning like

> Warning: Attempt to close dangling TCP connection to xxx.xxx.xxx.xxx:80 at shutdown. Please avoid closing connections in GC finalizers.

With ssl requests probably more serious problems lead to segfault.

So if your code looks like this (correct me if I'm wrong):
```d
import vibe.d;
import requests;

class RestClient {
     Request rq;

     this(string user, string passwd) {
         rq.verbosity = 0;
         rq.authenticator = new BasicAuthentication(user, passwd);
     }

    auto Projects() {
        auto rs = rq.get("http://httpbin.org/get");
         //auto pr = parseJsonString(rs.responseBody.to!string);

         return rs.responseBody.to!string;
     }
}

shared static this()
{
    auto settings = new HTTPServerSettings;
    settings.port = 8080;
    settings.bindAddresses = ["::1", "127.0.0.1"];
    listenHTTP(settings, &hello);

    logInfo("Please open http://127.0.0.1:8080/ in your browser.");
}

void hello(HTTPServerRequest req, HTTPServerResponse res)
{
    auto rest = new RestClient("user", "pass");
    auto projects = rest.Projects();
    res.writeBody(projects);
}
```
then you can solve problem either setting rq.keepAlive = false or calling rest.destroy() before leaving hello() handler. Anyway keepalive requests in this case have no sense.

Please, inform if this helped.

**Comment by schancel** [comment] 2016-12-06 22:43
I was actually writing a command line tool.

```D
int main()
{
    auto tasks = iota(1).map!((x) => () {
        import stash;

        auto sc = new RestClient(user, passwd);
        auto projects = sc.Projects();
    }).map!((d) => runTask(d.toDelegate));

    runTask(() {
        tasks.each!( (task) { task.join(); });
        exitEventLoop();
    });
    return runEventLoop();
}
```

Pardon the odd code.  There was a reason for the task scaffolding.

**Comment by ikod** [comment] 2016-12-07 00:44
Ok, something like this should help:
```d
int main()
{
    auto tasks = iota(1).map!((x) => () {
        import restclient;

        auto sc = new RestClient(user, passwd);
        auto projects = sc.Projects();
        sc.destroy(); // <-- this should help
    }).map!((d) => runTask(d.toDelegate));

    runTask(() {
        tasks.each!( (task) { task.join(); });
        exitEventLoop();
    });
    return runEventLoop();
}
```
Or, if you prefer - configure rq.keepAlive = false in RestClient constructor.

**Comment by schancel** [comment] 2016-12-07 19:11
Thanks!

**Closed** 2016-12-08 09:27 UTC
