### ISSUE TITLE
Simple example causes program to crash with exit code -4

### ISSUE THREAD

**Issue by forbjok** [ikod/dlang-requests#85] opened 2018-12-01 11:29 UTC
As the title says, trying to execute what is basically just one of the examples from the README, causes the program to crash with exit code -4.

The OS is a 64-bit Arch Linux installation. (up to date as of today)
DMD is v2.083.0.

Here's a repository containing the reproduction project: https://github.com/forbjok/dlang-requests-repro

![putty_2018-12-01_12-21-58](https://user-images.githubusercontent.com/4687674/49327675-2caefb80-f564-11e8-9253-f5f4c39f1c2a.png)

As seen in the image, the program starts executing, as it prints the BEFORE text, but crashes upon trying to do the request, before it can print the AFTER text.

**Comment by ikod** [comment] 2018-12-01 12:13
Hello,

Will look in few hours.

сб, 1 дек. 2018 г., 13:29 forbjok notifications@github.com:

**Comment by forbjok** [comment] 2018-12-01 14:15
I tested with LDC2 and found that it works with that, so this seems to be a compiler-specific compatibility issue with this library and DMD.

**Comment by forbjok** [comment] 2018-12-01 15:07
Output of running "dub run -v":
[dub-v.txt](https://github.com/ikod/dlang-requests/files/2635969/dub-v.txt)

Output of running the executable directly:
![putty_2018-12-01_16-04-43](https://user-images.githubusercontent.com/4687674/49329687-03ea2e80-f583-11e8-9262-4ca07fe4fcb4.png)

**Comment by ikod** [comment] 2018-12-01 17:02
Hello @forbjok 

would be nice to run
gdb ./dlang-requests-repro
wait for illegal instruction and issue gdb command
bt

**Comment by forbjok** [comment] 2018-12-01 22:13
![putty_2018-12-01_23-01-45](https://user-images.githubusercontent.com/4687674/49333406-a07df200-f5be-11e8-8c44-b1328763933c.png)

**Comment by ikod** [comment] 2018-12-02 05:32
Hello,

Thanks for screenshot. It's funny. And it means that popcnt in dmd uses
illegal instruction. I think it is bug in dmd or in package building for
64bit Archlinux . I'll try to investigate today later.


вс, 2 дек. 2018 г., 0:13 forbjok notifications@github.com:

**Comment by ikod** [comment] 2018-12-03 08:30
Hello, @forbjok 

I'm going to close this issue as it seems not a dlang-requests problem.  I can't reproduce it in my env. Probably you can narrow issue to app with single `popcnt` call.

**Comment by ikod** [comment] 2018-12-03 10:37
hello @forbjok 
Yes, in debug mode this popcnt call is omitted, so this was another test for problem source. This can be dmd/CPU combination problem. BTW, what is your CPU?

**Comment by ikod** [comment] 2018-12-03 18:44
ok, I'm closing it

**Closed by ikod** 2018-12-03 18:44 UTC

**Comment by forbjok** [comment] 2018-12-05 09:49
The CPU on the machine I've been testing on is an older Intel Core 2 Quad Q9550.

**Comment by ikod** [comment] 2018-12-05 10:29
Then probably dmd use illegal instruction for this cpu. I'm mostly sure
that it is some kind of dmd backend bug, but I have no such cpu to check.

I can actually try to change contract in order not to use popcnt, as it
must not hurt performance in release mode anyway. Do you really need it?

ср, 5 дек. 2018 г., 11:49 forbjok notifications@github.com:

**Comment by forbjok** [comment] 2018-12-06 11:17
I will see if I can test it on another newer machine with an i7 7700k with Antergos (a variant of Arch Linux) later today to see if it is actually CPU specific.
If it's CPU specific, it's not really critical for me.
The old machine will be replaced fairly soon, and it's running in debug mode right now.

**Comment by ikod** [comment] 2018-12-06 12:03
Ok, will wait for your test.

чт, 6 дек. 2018 г., 13:17 forbjok notifications@github.com:

**Comment by forbjok** [comment] 2018-12-06 17:23
I tested it, and I can't reproduce it on the i7 7700k machine, so it does seem to be CPU-specific.

**Comment by ikod** [comment] 2018-12-06 18:45
Hello @forbjok 

Great, so my theory is correct - dmd produce machine code for popcnt which can't be executed on your cpu. Do not know if this can be fixed, but probably it is worth to report details on dmd bugzilla.

**Comment by ikod** [comment] 2018-12-11 12:22
Hello,

I changed call to _popcnt to popcnt - it was my fault to use non-portable api from std library.
should be fixed in next release.
