### ISSUE TITLE
Chunked transfers hang if stream fits into first read 

### ISSUE THREAD

**Issue by Timbus** [ikod/dlang-requests#70] opened 2018-04-04 05:19 UTC
Hello,
I've noticed if you use streaming APIs, this library hangs if the first chunk returned is smaller than 4096 bytes. The reason is that in [http.d:919](https://github.com/ikod/dlang-requests/blob/master/source/requests/http.d#L919) you are storing the leftover body after parsing the headers, but you are not setting `_response._responseBody`, which means the reader is never called on the first loop [here](https://github.com/ikod/dlang-requests/blob/master/source/requests/http.d#L936).

That means the stream reader will hang [on line 1002](https://github.com/ikod/dlang-requests/blob/master/source/requests/http.d#L1002) until the next chunk arrives, which might be never!

My guess is you need to insert the partialbody into the `_responseBody`? Or change the condition.

**Comment by ikod** [comment] 2018-04-04 06:16
Hello @Timbus ,

Thanks for report, will check and fix it today later

**Comment by ikod** [comment] 2018-04-04 21:00
Hello again @Timbus 

> if the first chunk returned is smaller than 4096 bytes

Do you mean - we received only part of first HTTP transfer-encoding chunk? Yes, in this case we will have empty responseBody (until we receive rest of the chunk)

> but you are not setting _response._responseBody, which means the reader is never called on the first loop here.

No - in this case condition

`_useStreaming && _response._responseBody.length && !redirectCodes.canFind(_response.code`

will fail and we pass to the [line](https://github.com/ikod/dlang-requests/blob/master/source/requests/http.d#L1001) where we read next portion of the chunk from the network. We will run loop at line 928 until we complete first chunk, so that we can return to caller and continue streaming.

So yes, in streaming mode we can return to caller only as soon as we received first complete HTTP content-encoding chunk. If we received only part of this chunk, then we will continue to read it from network and return to caller on the next iteratioin.

Do you think this is a problem or I missed the point?

**Comment by ikod** [comment] 2018-04-04 21:26
Just to be sure - you'd like to receive first part of the chunk regardless
of any forther data. Right?

чт, 5 Апр 2018 г., 0:23 Igor Khasilev <igor.khasilev@gmail.com>:

**Comment by ikod** [comment] 2018-04-04 21:41
Anyway at least api response headers will help to solve problem. Thanks

чт, 5 Апр 2018 г., 0:26 Igor Khasilev <igor.khasilev@gmail.com>:

**Comment by Timbus** [comment] 2018-04-04 21:54
Yeah the response data is just a few lines of JSON structs, but they contain possibly sensitive data, so I'll have to skip that:
```
2018-04-05T07:52:54.647:http.d:setupConnection:809 Set up new connection
2018-04-05T07:52:54.647:http.d:select_proxy:446 proxy=null
2018-04-05T07:52:54.647:streams.d:connect:998 Create connection to 127.0.0.1:8001
2018-04-05T07:52:54.648:streams.d:connect:1007 Trying 127.0.0.1:8001
2018-04-05T07:52:54.649:streams.d:connect:1017 Connected to 127.0.0.1:8001
2018-04-05T07:52:54.649:http.d:select_proxy:446 proxy=null
2018-04-05T07:52:54.649:http.d:exec:1383 GET /apis/extensions/v1beta1/watch/ingresses?&timeoutSeconds=86400 HTTP/1.1
User-Agent: dlang-requests
Accept-Encoding: gzip,deflate
Connection: Keep-Alive
Host: 127.0.0.1:8001


> GET /apis/extensions/v1beta1/watch/ingresses?&timeoutSeconds=86400 HTTP/1.1
> User-Agent: dlang-requests
> Accept-Encoding: gzip,deflate
> Connection: Keep-Alive
> Host: 127.0.0.1:8001
>
2018-04-05T07:52:55.010:http.d:receiveResponse:894 read: 3851
00000  48 54 54 50 2F 31 2E 31  20 32 30 30 20 4F 4B 0D  |HTTP/1.1 200 OK.|
--- [snipped] ---
00F00  39 22 7D 5D 7D 7D 7D 7D  0A 0D 0A                 |9"}]}}}}...     |
2018-04-05T07:52:55.016:http.d:parseResponseHeaders:623 statusLine: HTTP/1.1 200 OK
< HTTP/1.1 200 OK
< content-type: application/json
2018-04-05T07:52:55.016:http.d:parseResponseHeaders:650 Header content-type = application/json
< date: Wed, 04 Apr 2018 21:52:54 GMT
2018-04-05T07:52:55.017:http.d:parseResponseHeaders:650 Header date = Wed, 04 Apr 2018 21:52:54 GMT
< transfer-encoding: chunked
2018-04-05T07:52:55.017:http.d:parseResponseHeaders:650 Header transfer-encoding = chunked
2018-04-05T07:52:55.017:http.d:analyzeHeaders:593 transferEncoding: chunked
2018-04-05T07:52:55.017:streams.d:empty:308 empty=0
2018-04-05T07:52:55.017:streams.d:empty:308 empty=1
< 3735 bytes of body received
```
That's it. It is now stuck on line 1002.

**Comment by ikod** [comment] 2018-04-04 21:59
Thanks, this is what I need. Need some time to reproduce and fix.

2018-04-05 0:54 GMT+03:00 Jarrod Funnell <notifications@github.com>:

**Comment by Timbus** [comment] 2018-04-04 22:34
My temporary fix was to just insert the partialbody into _response._responseBody after the header loop, using putNoCopy. Seems to work for my project.

**Comment by ikod** [comment] 2018-04-04 22:43
Can you please check current github master? I think it should be fixed.
Looks like the same fix as you proposed.

2018-04-05 1:34 GMT+03:00 Jarrod Funnell <notifications@github.com>:

**Comment by Timbus** [comment] 2018-04-04 22:57
It works! Thank you for this.

**Comment by ikod** [comment] 2018-04-04 23:01
thank you for bugreport!

will close issue

2018-04-05 1:57 GMT+03:00 Jarrod Funnell <notifications@github.com>:

**Closed** 2018-04-04 23:01 UTC
